### ISSUE TITLE
Can you add support for yaml format?

### ISSUE THREAD

**Issue by hillz2** [MrMohebi/xray-proxy-grabber-telegram#3]
Hi, I love this repo but unfortunately I have to add every proxy manually to openclash ? It's very time consuming, can you provide a yaml file so that on openclash I can just add a static URL to your yaml file to update the proxies automatically ?

**Comment by MrMohebi** [comment]
requested feature added in #4

**Comment by hillz2** [comment]
Thank you I really appreciate it
